// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn2BHJr0C2cSy1HIt1cgmwzQ0TcWXMy3w',
    appId: '1:46859162101:web:a87a92a427556d510a10bc',
    messagingSenderId: '46859162101',
    projectId: 'firebale-example',
    authDomain: 'firebale-example.firebaseapp.com',
    storageBucket: 'firebale-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnlhJ-pcQtQZbSmnjmYOW1nUUjsjEbX20',
    appId: '1:46859162101:android:be54a744427ef5c30a10bc',
    messagingSenderId: '46859162101',
    projectId: 'firebale-example',
    storageBucket: 'firebale-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHZjS9U4xkqJWL6SMf9UOveLdTRtqrWvc',
    appId: '1:46859162101:ios:10e196752c06928c0a10bc',
    messagingSenderId: '46859162101',
    projectId: 'firebale-example',
    storageBucket: 'firebale-example.appspot.com',
    iosClientId: '46859162101-cncce9f9f6q6531kfprqhoajicqbba4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHZjS9U4xkqJWL6SMf9UOveLdTRtqrWvc',
    appId: '1:46859162101:ios:10e196752c06928c0a10bc',
    messagingSenderId: '46859162101',
    projectId: 'firebale-example',
    storageBucket: 'firebale-example.appspot.com',
    iosClientId: '46859162101-cncce9f9f6q6531kfprqhoajicqbba4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn2BHJr0C2cSy1HIt1cgmwzQ0TcWXMy3w',
    appId: '1:46859162101:web:237f5967703f34c50a10bc',
    messagingSenderId: '46859162101',
    projectId: 'firebale-example',
    authDomain: 'firebale-example.firebaseapp.com',
    storageBucket: 'firebale-example.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCn2BHJr0C2cSy1HIt1cgmwzQ0TcWXMy3w',
    appId: '1:46859162101:web:9ca6c0160dd791080a10bc',
    messagingSenderId: '46859162101',
    projectId: 'firebale-example',
    authDomain: 'firebale-example.firebaseapp.com',
    storageBucket: 'firebale-example.appspot.com',
  );
}
